=== api-evangelist/amazon-global-accelerator/json-schema/global-accelerator-endpoint-group-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-global-accelerator/refs/heads/main/json-schema/global-accelerator-endpoint-group-schema.json",
  "title": "EndpointGroup",
  "description": "A complex type for the endpoint group. An Amazon Web Services Region can have only one endpoint group for a specific listener. ",
  "type": "object",
  "properties": {
    "EndpointGroupArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GenericString"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the endpoint group."
        }
      ]
    },
    "EndpointGroupRegion": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GenericString"
        },
        {
          "description": "The Amazon Web Services Region where the endpoint group is located."
        }
      ]
    },
    "EndpointDescriptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EndpointDescriptions"
        },
        {
          "description": "The list of endpoint objects."
        }
      ]
    },
    "TrafficDialPercentage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TrafficDialPercentage"
        },
        {
          "description": "<p>The percentage of traffic to send to an Amazon Web Services Region. Additional traffic is distributed to other endpoint groups for this listener. </p> <p>Use this action to increase (dial up) or decrease (dial down) traffic to a specific Region. The percentage is applied to the traffic that would otherwise have been routed to the Region based on optimal routing.</p> <p>The default value is 100.</p>"
        }
      ]
    },
    "HealthCheckPort": {
      "allOf": [
        {
          "$ref": "#/components/schemas/HealthCheckPort"
        },
        {
          "description": "<p>The port that Global Accelerator uses to perform health checks on endpoints that are part of this endpoint group. </p> <p>The default port is the port for the listener that this endpoint group is associated with. If the listener port is a list, Global Accelerator uses the first specified port in the list of ports.</p>"
        }
      ]
    },
    "HealthCheckProtocol": {
      "allOf": [
        {
          "$ref": "#/components/schemas/HealthCheckProtocol"
        },
        {
          "description": "The protocol that Global Accelerator uses to perform health checks on endpoints that are part of this endpoint group. The default value is TCP."
        }
      ]
    },
    "HealthCheckPath": {
      "allOf": [
        {
          "$ref": "#/components/schemas/HealthCheckPath"
        },
        {
          "description": "If the protocol is HTTP/S, then this value provides the ping path that Global Accelerator uses for the destination on the endpoints for health checks. The default is slash (/)."
        }
      ]
    },
    "HealthCheckIntervalSeconds": {
      "allOf": [
        {
          "$ref": "#/components/schemas/HealthCheckIntervalSeconds"
        },
        {
          "description": "The time\u201410 seconds or 30 seconds\u2014between health checks for each endpoint. The default value is 30."
        }
      ]
    },
    "ThresholdCount": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ThresholdCount"
        },
        {
          "description": "The number of consecutive health checks required to set the state of a healthy endpoint to unhealthy, or to set an unhealthy endpoint to healthy. The default value is 3."
        }
      ]
    },
    "PortOverrides": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PortOverrides"
        },
        {
          "description": "Allows you to override the destination ports used to route traffic to an endpoint. Using a port override lets you map a list of external destination ports (that your users send traffic to) to a list of internal destination ports that you want an application endpoint to receive traffic on. "
        }
      ]
    }
  }
}

=== api-evangelist/amazon-global-accelerator/examples/global-accelerator-endpoint-group-example.json
{
  "EndpointGroupArn": "arn:aws:globalaccelerator::123456789012:accelerator/abc-123",
  "EndpointGroupRegion": "us-east-1",
  "EndpointDescriptions": "1.2.3.4",
  "TrafficDialPercentage": "example-TrafficDialPerc",
  "HealthCheckPort": "example-HealthCheckPort",
  "HealthCheckProtocol": "example-HealthCheckProt",
  "HealthCheckPath": "example-HealthCheckPath",
  "HealthCheckIntervalSeconds": "example-HealthCheckInte"
}
