=== api-evangelist/amazon-global-accelerator/json-schema/global-accelerator-port-mapping-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-global-accelerator/refs/heads/main/json-schema/global-accelerator-port-mapping-schema.json",
  "title": "PortMapping",
  "description": "Returns the ports and associated IP addresses and ports of Amazon EC2 instances in your virtual private cloud (VPC) subnets. Custom routing is a port mapping protocol in Global Accelerator that statically associates port ranges with VPC subnets, which allows Global Accelerator to route to specific instances and ports within one or more subnets. ",
  "type": "object",
  "properties": {
    "AcceleratorPort": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PortNumber"
        },
        {
          "description": "The accelerator port."
        }
      ]
    },
    "EndpointGroupArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GenericString"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the endpoint group."
        }
      ]
    },
    "EndpointId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GenericString"
        },
        {
          "description": "The IP address of the VPC subnet (the subnet ID)."
        }
      ]
    },
    "DestinationSocketAddress": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SocketAddress"
        },
        {
          "description": "The EC2 instance IP address and port number in the virtual private cloud (VPC) subnet."
        }
      ]
    },
    "Protocols": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CustomRoutingProtocols"
        },
        {
          "description": "The protocols supported by the endpoint group."
        }
      ]
    },
    "DestinationTrafficState": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CustomRoutingDestinationTrafficState"
        },
        {
          "description": "Indicates whether or not a port mapping destination can receive traffic. The value is either ALLOW, if traffic is allowed to the destination, or DENY, if traffic is not allowed to the destination."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-global-accelerator/examples/global-accelerator-port-mapping-example.json
{
  "AcceleratorPort": "example-AcceleratorPort",
  "EndpointGroupArn": "arn:aws:globalaccelerator::123456789012:accelerator/abc-123",
  "EndpointId": "example-EndpointId",
  "DestinationSocketAddress": "example-DestinationSock",
  "Protocols": "example-Protocols",
  "DestinationTrafficState": "example-DestinationTraf"
}
